### ISSUE TITLE
Bug with a long run of PusherClient

### ISSUE THREAD

**Issue by Nono242** [ekulyk/PythonPusherClient#14]
Here below is the error message :

Unhandled exception in thread started by <bound method Connection.run of <Connection(Thread-1, initial)>>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pusherclient-0.2.0-py2.7.egg/pusherclient/connection.py", line 88, in run
    self._connect()
  File "/usr/local/lib/python2.7/dist-packages/pusherclient-0.2.0-py2.7.egg/pusherclient/connection.py", line 111, in _connect
    self.socket.run_forever()
  File "/usr/local/lib/python2.7/dist-packages/websocket/_app.py", line 179, in run_forever
    self.sock.close()
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 810, in close
    self._closeInternal()
  File "/usr/local/lib/python2.7/dist-packages/websocket/_core.py", line 813, in _closeInternal
    self.sock.close()
AttributeError: 'NoneType' object has no attribute 'close'

Thankx to have a look on it,
Arnaud

**Comment by Nono242** [comment]
I got the problems again a few times. The problem appears when my modem got a disconnect and reestablish a connection  back.

Arnaud

**Comment by ekulyk** [comment]
I'm able to reproduce this issue with the latest pusher-client and websocket-client-0.18.  This reconnect feature used to work at some time in the past when I tested it ~4years ago.  I will see if I can get it fixed.

**Comment by ekulyk** [comment]
Hi Arnaud,

I was able to reproduce the issue by disconnecting my wireless dongle when the connection was waiting for information from Pusher.  After the original web socket timed out, it would attempt to reconnect by calling run_forever on the same websocket object which would show the exception you supplied.

After forcing websocket-client to check the internal state of the socket object before closing, the exception no longer happens.  Pusherclient will now automatically reconnect as it once did.

You can see the state of the pull request at liris/websocket-client#115.

**Comment by Nono242** [comment]
Thank you very much for the effort. I've updated my Pusher client.

Arnaud

**Comment by ekulyk** [comment]
"""
After update of the websocket-client , I've now this error message from the reading thread:
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
self.run()
File "/usr/local/lib/python2.7/dist-packages/pusherclient-0.2.0-py2.7.egg/pusherclient/connection.py", line 89, in run
self._connect()
File "/usr/local/lib/python2.7/dist-packages/pusherclient-0.2.0-py2.7.egg/pusherclient/connection.py", line 94, in _connect
self.socket = websocket.WebSocketApp(
AttributeError: 'module' object has no attribute 'WebSocketApp'
"""

Hi Arnaud,

This error doesn't seem right.  Please check your install (Multiple websocket modules installed, installed wrong version?).  If you look at **init**.py in liris's websocket module. you'll see that WebSocketApp is imported there so there should be no issues.

If you do the following:
import websocket
dir(websocket)

You should see WebSocketApp as one of the entries in the list.

**Comment by Nono242** [comment]
Hello ekulyk,

I thought my message was deleted ... I had to reinstall websocket-client from Liris; After that I didn't have the error anymore. The websocket had been rebuilt before the error occured.

Thank you for the answer.

Arnaud
